version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
        key: m2
      - run: mvn -B -V -T 1C verify
      - save_cache:
        paths:
          - ~/.m2
        key: m2